# Generated by Django 5.0.6 on 2024-11-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0004_alter_post_options_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='Type',
        ),
    ]
